name: Close inactive issues

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
      - uses: actions/stale@v10
        with:
          # Ждем 14 дней без активности
          days-before-issue-stale: 14
          # Ждем 1 день после получения метки перед закрытием (минимальное значение)
          days-before-issue-close: 1

          stale-issue-label: 'без активности'
          # Эта опция уберет метку, если в issue снова начнут писать
          remove-stale-when-updated: true

          # Сообщение при закрытии (оставьте пустым, если не нужно предупреждение)
          stale-issue-message: 'Этот issue помечен как устаревший из-за отсутствия активности в течение 14 дней. Он будет автоматически закрыт через 1 день, если не будет обновлен.'
          close-issue-message: 'Закрыто автоматически из-за отсутствия активности в течение 14 дней.'

          # Отключаем для Pull Request'ов
          days-before-pr-stale: -1
          days-before-pr-close: -1
